# Publishes PyPI release on v{version} tags
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test-release:
    name: Release Package to test PyPI
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --only main

      - name: Build and publish to test PyPI
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.POETRY_PYPI_TOKEN }}
          poetry publish -r test-pypi --build

  release:
    name: Release Package to PyPI
    runs-on: ubuntu-latest
    environment: main
    needs: test-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --only main

      - name: Build and publish to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_PROD_TOKEN }}
          poetry publish --build
